/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{md,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#1a1d21',
        cursor: '#6FC1FF',
        'gray-850': '#1f2937',
        'gray-750': '#374151',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'Monaco', 'Menlo', 'Courier New', 'monospace'],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': '#d1d5db',
            '--tw-prose-headings': '#ffffff',
            '--tw-prose-lead': '#9ca3af',
            '--tw-prose-links': '#6FC1FF',
            '--tw-prose-bold': '#ffffff',
            '--tw-prose-counters': '#9ca3af',
            '--tw-prose-bullets': '#6FC1FF',
            '--tw-prose-hr': '#374151',
            '--tw-prose-quotes': '#d1d5db',
            '--tw-prose-quote-borders': '#6FC1FF',
            '--tw-prose-captions': '#9ca3af',
            '--tw-prose-code': '#6FC1FF',
            '--tw-prose-pre-code': '#e6edf3',
            '--tw-prose-pre-bg': '#0d1117',
            '--tw-prose-th-borders': '#374151',
            '--tw-prose-td-borders': '#374151',
            maxWidth: 'none',
            fontSize: '1.1rem',
            lineHeight: '1.8',
            color: 'var(--tw-prose-body)',
            p: {
              marginBottom: '1.5rem',
              lineHeight: '1.8',
            },
            h1: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '700',
              fontSize: '2.5rem',
              marginTop: '0',
              marginBottom: '2rem',
              borderBottom: '3px solid #6FC1FF',
              paddingBottom: '0.5rem',
            },
            h2: {
              color: 'var(--tw-prose-headings)',
              fontWeight: '700',
              fontSize: '2rem',
              marginTop: '3rem',
              marginBottom: '1.5rem',
              borderBottom: '2px solid #374151',
              paddingBottom: '0.5rem',
            },
            h3: {
              color: '#6FC1FF',
              fontWeight: '700',
              fontSize: '1.75rem',
              marginTop: '3rem',
              marginBottom: '1.5rem',
            },
            a: {
              color: 'var(--tw-prose-links)',
              textDecoration: 'underline',
              textDecorationColor: 'rgba(111, 193, 255, 0.3)',
              textUnderlineOffset: '3px',
              textDecorationThickness: '1px',
              '&:hover': {
                textDecorationColor: '#6FC1FF',
                textDecorationThickness: '2px',
              },
            },
            code: {
              color: 'var(--tw-prose-code)',
              backgroundColor: '#374151',
              padding: '0.25rem 0.5rem',
              borderRadius: '0.375rem',
              fontSize: '0.9rem',
              fontWeight: '500',
              border: '1px solid #4b5563',
              '&::before': {
                content: '""',
              },
              '&::after': {
                content: '""',
              },
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              backgroundColor: 'var(--tw-prose-pre-bg)',
              color: 'var(--tw-prose-pre-code)',
              border: '1px solid #30363d',
              borderRadius: '1rem',
              padding: '2rem',
              margin: '2.5rem 0',
              fontSize: '0.9rem',
              lineHeight: '1.7',
              boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
              position: 'relative',
              '&::before': {
                content: '""',
                position: 'absolute',
                top: '0',
                left: '0',
                right: '0',
                height: '4px',
                background: 'linear-gradient(90deg, #6FC1FF 0%, #8B5CF6 50%, #06B6D4 100%)',
                borderRadius: '1rem 1rem 0 0',
              },
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              fontSize: 'inherit',
              fontWeight: 'normal',
              padding: '0',
              border: 'none',
            },
            blockquote: {
              borderLeft: '4px solid #6FC1FF',
              paddingLeft: '1.5rem',
              margin: '2rem 0',
              fontStyle: 'italic',
              backgroundColor: 'rgba(111, 193, 255, 0.05)',
              padding: '1.5rem',
              borderRadius: '0.75rem',
              position: 'relative',
              '&::before': {
                content: '"""',
                position: 'absolute',
                top: '0.5rem',
                left: '0.5rem',
                fontSize: '3rem',
                color: '#6FC1FF',
                opacity: '0.3',
                lineHeight: '1',
              },
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}